name: API CI
#on: [push]

# config monolito
on:
  [push]:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"
defaults:
  run:
    working-directory: ./api
# config monolito

jobs:
  unitest:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with: 
          node-versison: 14
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: Install
        shell: bash
        run: npm ci #npm install
      - name: Run unit test
        shell: bash
        run: npm run test