name: API CI

# config monolito
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"
defaults:
  run:
    working-directory: ./api
# config monolito

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'pnpm'
        # monolito
        cache-dependency-path: ./api/pnpm-lock.yaml
    - name: install pnpm
      shell: bash
      run: npm install -g pnpm
    - name: install dependencies pnpm
      shell: bash
      run: pnpm install
    - name: run unit test
      shell: bash
      run: pnpm test
