name: API CI

# config monolito
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"
defaults:
  run:
    working-directory: ./api
# config monolito

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18
        cache: 'npm'
        # monolito
        cache-dependency-path: ./api/package-lock.json
    - name: install
      shell: bash
      run: npm ci
    - name: run unit test
      shell: bash
      run: npm test
