name: API CI

# config monolito
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"
defaults:
  run:
    working-directory: ./api
# config monolito

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        # monolito
        cache-dependency-path: ./api/pnpm-lock.yaml
    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm
    - name: Install dependencies pnpm
      shell: bash
      run: pnpm install --no-frozen-lockfile
    - name: Run unit test
      shell: bash
      run: pnpm test

  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        # monolito
        cache-dependency-path: ./api/pnpm-lock.yaml
    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm
    - name: Install dependencies pnpm
      shell: bash
      run: pnpm install --no-frozen-lockfile
    - name: Run e2e test
      shell: bash
      run: pnpm test:e2e

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        # monolito
        cache-dependency-path: ./api/pnpm-lock.yaml
    - name: Install pnpm
      shell: bash
      run: npm install -g pnpm
    - name: Install dependencies pnpm
      shell: bash
      run: pnpm install --no-frozen-lockfile
    - name: Run eslint
      shell: bash
      run: pnpm lint:fix